        
// ArgLabel.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class ArgLabel: CustomStringConvertible {
	
	let label: String
	
	init(_ label: String) {
		self.label = label
	}

	public var description: String {
		label.description + " "
	}
	
}
