        
// ArgLabelLabel.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class ArgLabelLabel: CustomStringConvertible {
	
	let callee: String
	let ret: String
	
	init(_ callee: String, _ ret: String) {
		self.callee = callee
		self.ret = ret
	}

	public var description: String {
		callee.description + " " + ", " + ret.description + " "
	}
	
}
