        
// ArgRegImmReg.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class ArgRegImmReg: CustomStringConvertible {
	
	let ra: String
	let imm: String
	let rb: String
	
	init(_ ra: String, _ imm: String, _ rb: String) {
		self.ra = ra
		self.imm = imm
		self.rb = rb
	}

	public var description: String {
		ra.description + " " + ", " + imm.description + " " + ", " + rb.description + " "
	}
	
}
