        
// ArgRegRegReg.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class ArgRegRegReg: CustomStringConvertible {
	
	let ra: String
	let rb: String
	let rc: String
	
	init(_ ra: String, _ rb: String, _ rc: String) {
		self.ra = ra
		self.rb = rb
		self.rc = rc
	}

	public var description: String {
		ra.description + " " + ", " + rb.description + " " + ", " + rc.description + " "
	}
	
}
