        
// ArgRegImm.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class ArgRegImm: CustomStringConvertible {
	
	let reg: String
	let imm: String
	
	init(_ reg: String, _ imm: String) {
		self.reg = reg
		self.imm = imm
	}

	public var description: String {
		reg.description + " " + ", " + imm.description + " "
	}
	
}
