        
// ArgReg.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class ArgReg: CustomStringConvertible {
	
	let reg: String
	
	init(_ reg: String) {
		self.reg = reg
	}

	public var description: String {
		reg.description + " "
	}
	
}
