        
// Args.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public enum Args: CustomStringConvertible {
	
	case argRegRegReg(ArgRegRegReg)
	case argRegRegImm(ArgRegRegImm)
	case argRegImmReg(ArgRegImmReg)
	case argRegImm(ArgRegImm)
	case argRegReg(ArgRegReg)
	case argLabel(ArgLabel)
	case argRegLabel(ArgRegLabel)
	case argReg(ArgReg)
	
	public var description: String {
		switch self {
		case .argRegRegReg(let argRegRegReg): return argRegRegReg.description
		case .argRegRegImm(let argRegRegImm): return argRegRegImm.description
		case .argRegImmReg(let argRegImmReg): return argRegImmReg.description
		case .argRegImm(let argRegImm): return argRegImm.description
		case .argRegReg(let argRegReg): return argRegReg.description
		case .argLabel(let argLabel): return argLabel.description
		case .argRegLabel(let argRegLabel): return argRegLabel.description
		case .argReg(let argReg): return argReg.description
		}
	}
	
}
