        
// Data.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class Data: CustomStringConvertible {
	
	let words: Words
	
	init(_ words: Words) {
		self.words = words
	}

	public var description: String {
		"datasegment " + "{ " + words.description + " " + "} "
	}
	
}
