        
// Instruction.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class Instruction: CustomStringConvertible {
	
	let opcode: String
	let args: Args
	
	init(_ opcode: String, _ args: Args) {
		self.opcode = opcode
		self.args = args
	}

	public var description: String {
		opcode.description + " " + args.description + " "
	}
	
}
