        
// Label.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public class Label: CustomStringConvertible {
	
	let name: String
	let instructions: Instructions
	
	init(_ name: String, _ instructions: Instructions) {
		self.name = name
		self.instructions = instructions
	}

	public var description: String {
		"@ " + name.description + " " + ": " + instructions.description + " "
	}
	
}
