        
// Statement.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

public enum Statement: CustomStringConvertible {
	
	case label(Label)
	case data(Data)
	
	public var description: String {
		switch self {
		case .label(let label): return label.description
		case .data(let data): return data.description
		}
	}
	
}
